if(NOT WIN32 OR NOT CMAKE_GENERATOR STREQUAL "Visual Studio 18 2026")
    message(FATAL_ERROR "Manual components require the active Visual Studio 2026 Windows toolchain")
endif()
if(NOT CMAKE_CONFIGURATION_TYPES STREQUAL "Debug;Release" OR NOT CMAKE_GENERATOR_PLATFORM STREQUAL "x64")
    message(FATAL_ERROR "Manual components require exactly Debug;Release and x64")
endif()
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin/$<CONFIG>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin/$<CONFIG>")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/lib/$<CONFIG>")
get_filename_component(default_component_root "${PROJECT_BINARY_DIR}" DIRECTORY)
set(ELF3D_COMPONENT_ROOT "${default_component_root}" CACHE PATH "Private root containing the four manual components")
file(REAL_PATH "${ELF3D_COMPONENT_ROOT}/${ELF3D_BUILD_COMPONENT}" expected_binary)
file(REAL_PATH "${PROJECT_BINARY_DIR}" actual_binary)
if(NOT expected_binary STREQUAL actual_binary)
    message(FATAL_ERROR "Component build directory must be ${ELF3D_COMPONENT_ROOT}/${ELF3D_BUILD_COMPONENT}")
endif()
# These normal variables override any stale cache opt-ins before targets exist.
set(BUILD_TESTING OFF)
set(ELF3D_BUILD_TESTING OFF)
set(ELF3D_BUILD_ENGINE ON)
set(ELF3D_BUILD_APP ON)
include("${CMAKE_CURRENT_LIST_DIR}/dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/local-components.cmake")

set(model_dependencies elf3d_third_party_zlib elf3d_third_party_png
    elf3d_third_party_jpeg elf3d_third_party_cgltf elf3d_third_party_mikktspace)
if(ELF3D_BUILD_COMPONENT STREQUAL "dependencies")
    elf3d_add_model_dependencies()
    elf3d_add_glad()
    elf3d_add_glfw()
    # In this producer GLFW is part of the default build, rather than merely
    # an EXCLUDE_FROM_ALL dependency of an application.
    set_target_properties(glfw PROPERTIES EXCLUDE_FROM_ALL OFF EXCLUDE_FROM_DEFAULT_BUILD OFF)
    elf3d_write_component(dependencies ${model_dependencies} elf3d_third_party_glad glfw)
    return()
endif()

find_package(Threads REQUIRED)
elf3d_import_component(dependencies)
if(ELF3D_BUILD_COMPONENT STREQUAL "engine")
    add_subdirectory(modules)
    add_subdirectory(facade/elf3d)
    elf3d_write_component(engine elf3d elf3d_model)
    return()
endif()

find_package(OpenGL REQUIRED)
elf3d_import_component(engine)
if(ELF3D_BUILD_COMPONENT STREQUAL "imgui")
    elf3d_add_imgui()
    elf3d_check_prerequisites(elf3d_third_party_imgui glfw)
    add_subdirectory(integrations/imgui)
    elf3d_write_component(imgui elf3d_third_party_imgui elf3d_imgui)
    return()
endif()

elf3d_import_component(imgui)
add_subdirectory(framework/app)
add_subdirectory(apps/viewer)
set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT elf3d_viewer)
