# Each contract is the first and repeated include in an independent TU.
# No PCH or aggregate header can conceal a missing declaration dependency.
function(elf3d_add_header_contracts target)
    add_library(${target} OBJECT EXCLUDE_FROM_ALL)
    target_compile_features(${target} PRIVATE cxx_std_20)
    target_compile_definitions(${target} PRIVATE ELF3D_STATIC)
    set_target_properties(${target} PROPERTIES DISABLE_PRECOMPILE_HEADERS ON FOLDER "Elf3D/Tests")
    elf3d_enable_warnings(${target})
    set(combined "")
    foreach(header IN LISTS ARGN)
        file(RELATIVE_PATH relative "${PROJECT_SOURCE_DIR}" "${header}")
        string(MAKE_C_IDENTIFIER "${relative}" name)
        set(source "${CMAKE_CURRENT_BINARY_DIR}/header-contracts/${name}.cpp")
        file(GENERATE OUTPUT "${source}" CONTENT "#include \"${header}\"\n#include \"${header}\"\n")
        target_sources(${target} PRIVATE "${source}")
        string(APPEND combined "#include \"${header}\"\n#include \"${header}\"\n")
    endforeach()
    set(first "${CMAKE_CURRENT_BINARY_DIR}/header-contracts/${target}_combined.cpp")
    set(second "${CMAKE_CURRENT_BINARY_DIR}/header-contracts/${target}_odr.cpp")
    file(GENERATE OUTPUT "${first}" CONTENT "${combined}\nint main() { return 0; }\n")
    file(GENERATE OUTPUT "${second}" CONTENT "${combined}\nvoid elf3d_header_odr_probe() {}\n")
    add_executable(${target}_odr EXCLUDE_FROM_ALL "${first}" "${second}")
    target_compile_features(${target}_odr PRIVATE cxx_std_20)
    target_compile_definitions(${target}_odr PRIVATE ELF3D_STATIC)
    target_include_directories(${target}_odr PRIVATE "$<TARGET_PROPERTY:${target},INCLUDE_DIRECTORIES>")
    set_target_properties(${target}_odr PROPERTIES DISABLE_PRECOMPILE_HEADERS ON FOLDER "Elf3D/Tests")
    elf3d_enable_warnings(${target}_odr)
endfunction()
