# Group only sources already assigned to a target. This never discovers or
# compiles additional files and does not change include visibility.
function(elf3d_group_sources target_name)
    get_target_property(ide_sources ${target_name} SOURCES)
    foreach(source IN LISTS ide_sources)
        if(source MATCHES "\\$<")
            continue()
        endif()
        cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE)
        cmake_path(IS_PREFIX PROJECT_SOURCE_DIR "${source}" NORMALIZE in_source_tree)
        cmake_path(IS_PREFIX PROJECT_BINARY_DIR "${source}" NORMALIZE in_binary_tree)
        if(in_binary_tree)
            source_group("Generated Files" FILES "${source}")
        elseif(in_source_tree)
            source_group(TREE "${PROJECT_SOURCE_DIR}" FILES "${source}")
        endif()
    endforeach()
endfunction()
