# Private build-tree protocol. This is not an installable Elf3D package.
include_guard(GLOBAL)

function(elf3d_component_identity output)
    file(REAL_PATH "${ELF3D_SOURCE_ROOT}" source_root)
    file(REAL_PATH "${ELF3D_COMPONENT_ROOT}" component_root)
    file(SHA256 "${source_root}/CMakeLists.txt" composition)
    file(SHA256 "${source_root}/cmake/dependencies.cmake" dependencies)
    file(SHA256 "${source_root}/cmake/target-interfaces.cmake" interfaces)
    file(TO_CMAKE_PATH "${CMAKE_GENERATOR_INSTANCE}" instance)
    string(SHA256 identity
        "${source_root}|${component_root}|${composition}|${dependencies}|${interfaces}|${CMAKE_GENERATOR}|${CMAKE_GENERATOR_PLATFORM}|${CMAKE_GENERATOR_TOOLSET}|${instance}|${CMAKE_C_COMPILER}|${CMAKE_C_COMPILER_VERSION}|${CMAKE_CXX_COMPILER}|${CMAKE_CXX_COMPILER_VERSION}|${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}|${CMAKE_MSVC_RUNTIME_LIBRARY}|${CMAKE_CONFIGURATION_TYPES}")
    set(${output} "${identity}" PARENT_SCOPE)
endfunction()

function(elf3d_write_component component)
    elf3d_component_identity(identity)
    set(directory "${PROJECT_BINARY_DIR}/local")
    file(MAKE_DIRECTORY "${directory}")
    file(WRITE "${directory}/component.cmake"
        "set(elf3d_producer_identity [==[${identity}]==])\nset(elf3d_producer_targets [==[${ARGN}]==])\n")
    set(content "")
    foreach(target IN LISTS ARGN)
        get_target_property(type ${target} TYPE)
        string(APPEND content "set(${target}_type ${type})\nset(${target}_file [==[$<TARGET_FILE:${target}>]==])\n")
        if(type STREQUAL "SHARED_LIBRARY")
            string(APPEND content "set(${target}_implib [==[$<TARGET_LINKER_FILE:${target}>]==])\nset(${target}_pdb [==[$<TARGET_PDB_FILE:${target}>]==])\n")
        endif()
        # GLFW's own CMake owns its platform-specific public interface.
        if(target STREQUAL "glfw")
            foreach(property IN ITEMS INTERFACE_INCLUDE_DIRECTORIES INTERFACE_LINK_LIBRARIES INTERFACE_COMPILE_DEFINITIONS)
                string(APPEND content "set(glfw_${property} [==[$<TARGET_GENEX_EVAL:glfw,$<TARGET_PROPERTY:glfw,${property}>>]==])\n")
            endforeach()
        endif()
    endforeach()
    file(GENERATE OUTPUT "${directory}/artifacts-$<CONFIG>.cmake" CONTENT "${content}")
endfunction()

function(elf3d_import_component component)
    set(directory "${ELF3D_COMPONENT_ROOT}/${component}/local")
    if(NOT EXISTS "${directory}/component.cmake")
        message(FATAL_ERROR "Configure ${component} first with cmake/configure-win.ps1. Missing metadata: ${directory}/component.cmake")
    endif()
    include("${directory}/component.cmake")
    elf3d_component_identity(identity)
    if(NOT identity STREQUAL elf3d_producer_identity)
        message(FATAL_ERROR "Incompatible ${component} metadata: source root, component root, architecture, configurations, version or active toolchain differs. Regenerate all four solutions with cmake/configure-win.ps1 in the same root.")
    endif()
    if(ARGN)
        foreach(target IN LISTS ARGN)
            if(NOT target IN_LIST elf3d_producer_targets)
                message(FATAL_ERROR "${component} does not produce ${target}")
            endif()
        endforeach()
        set(elf3d_producer_targets ${ARGN})
    endif()
    foreach(configuration IN ITEMS Debug Release)
        include("${directory}/artifacts-${configuration}.cmake")
        string(TOUPPER "${configuration}" suffix)
        foreach(target IN LISTS elf3d_producer_targets)
            if(NOT TARGET ${target})
                if(${target}_type STREQUAL "SHARED_LIBRARY")
                    add_library(${target} SHARED IMPORTED GLOBAL)
                else()
                    add_library(${target} STATIC IMPORTED GLOBAL)
                endif()
                set_target_properties(${target} PROPERTIES
                    IMPORTED_CONFIGURATIONS "Debug;Release"
                    MAP_IMPORTED_CONFIG_DEBUG Debug MAP_IMPORTED_CONFIG_RELEASE Release
                    ELF3D_COMPONENT "${component}"
                    ELF3D_COMPONENT_SOLUTION "${ELF3D_COMPONENT_ROOT}/${component}/Elf3D-${component}.slnx"
                )
                # Canonical spelling is also used in build-time diagnostics.
                if(component STREQUAL "dependencies")
                    set_property(TARGET ${target} PROPERTY ELF3D_COMPONENT_SOLUTION "${ELF3D_COMPONENT_ROOT}/${component}/Elf3D-Dependencies.slnx")
                elseif(component STREQUAL "engine")
                    set_property(TARGET ${target} PROPERTY ELF3D_COMPONENT_SOLUTION "${ELF3D_COMPONENT_ROOT}/${component}/Elf3D-Engine.slnx")
                elseif(component STREQUAL "imgui")
                    set_property(TARGET ${target} PROPERTY ELF3D_COMPONENT_SOLUTION "${ELF3D_COMPONENT_ROOT}/${component}/Elf3D-ImGui.slnx")
                endif()
                elf3d_target_interface(${target})
            endif()
            set_property(TARGET ${target} PROPERTY IMPORTED_LOCATION_${suffix} "${${target}_file}")
            if(${target}_type STREQUAL "SHARED_LIBRARY")
                set_property(TARGET ${target} PROPERTY IMPORTED_IMPLIB_${suffix} "${${target}_implib}")
                set_property(TARGET ${target} PROPERTY ELF3D_PDB_${suffix} "${${target}_pdb}")
            endif()
            if(target STREQUAL "glfw")
                foreach(property IN ITEMS INTERFACE_INCLUDE_DIRECTORIES INTERFACE_LINK_LIBRARIES INTERFACE_COMPILE_DEFINITIONS)
                    if(configuration STREQUAL "Debug")
                        set_property(TARGET glfw PROPERTY ${property} "")
                    endif()
                    foreach(value IN LISTS glfw_${property})
                        set_property(TARGET glfw APPEND PROPERTY ${property} "$<$<CONFIG:${configuration}>:${value}>")
                    endforeach()
                endforeach()
            endif()
        endforeach()
    endforeach()
endfunction()

function(elf3d_check_prerequisites target)
    set(content "")
    foreach(dependency IN LISTS ARGN)
        get_target_property(component ${dependency} ELF3D_COMPONENT)
        get_target_property(solution ${dependency} ELF3D_COMPONENT_SOLUTION)
        set(paths "$<TARGET_FILE:${dependency}>")
        get_target_property(type ${dependency} TYPE)
        if(type STREQUAL "SHARED_LIBRARY")
            list(APPEND paths "$<TARGET_LINKER_FILE:${dependency}>")
        endif()
        foreach(path IN LISTS paths)
            string(APPEND content "if(NOT EXISTS [==[${path}]==])\n message(FATAL_ERROR [==[Missing prerequisite ${component} ($<CONFIG>): ${path}\nBuild ${solution} in $<CONFIG>|x64 first.]==])\nendif()\n")
        endforeach()
    endforeach()
    set(check "${PROJECT_BINARY_DIR}/local/${target}-$<CONFIG>-prerequisites.cmake")
    file(GENERATE OUTPUT "${check}" CONTENT "${content}")
    # OBJECT libraries do not support PRE_BUILD. A symbolic source rule runs
    # inside each existing project, also diagnosing deleted prerequisites on
    # an otherwise up-to-date build, without an extra utility project.
    set(rule "${CMAKE_CURRENT_BINARY_DIR}/${target}.prerequisites")
    add_custom_command(OUTPUT "${rule}" COMMAND "${CMAKE_COMMAND}" -P "${check}" VERBATIM)
    set_source_files_properties("${rule}" PROPERTIES SYMBOLIC TRUE)
    target_sources(${target} PRIVATE "${rule}")
endfunction()
