# Usage requirements are shared by source targets and checkout-local imports.
function(elf3d_private_libraries target)
    get_target_property(imported ${target} IMPORTED)
    if(imported)
        foreach(dependency IN LISTS ARGN)
            target_link_libraries(${target} INTERFACE "$<LINK_ONLY:${dependency}>")
        endforeach()
    else()
        target_link_libraries(${target} PRIVATE ${ARGN})
    endif()
endfunction()

function(elf3d_target_interface target)
    get_target_property(imported ${target} IMPORTED)
    if(imported)
        set(scope INTERFACE)
    else()
        set(scope PUBLIC)
    endif()
    if(target STREQUAL "elf3d_third_party_glad")
        target_include_directories(${target} SYSTEM ${scope} "${ELF3D_THIRD_PARTY_DIR}/glad/include")
        add_library(elf3d::third_party_glad ALIAS ${target})
    elseif(target STREQUAL "elf3d_third_party_zlib")
        target_include_directories(${target} SYSTEM ${scope} "${zlib_SOURCE_DIR}")
    elseif(target STREQUAL "elf3d_third_party_png")
        target_include_directories(${target} SYSTEM ${scope} "${libpng_SOURCE_DIR}")
        elf3d_private_libraries(${target} elf3d_third_party_zlib)
    elseif(target STREQUAL "elf3d_third_party_jpeg")
        target_include_directories(${target} SYSTEM ${scope} "${libjpeg_SOURCE_DIR}")
    elseif(target STREQUAL "elf3d_third_party_mikktspace")
        target_include_directories(${target} SYSTEM ${scope} "${mikktspace_SOURCE_DIR}")
    elseif(target STREQUAL "elf3d_third_party_imgui")
        target_compile_features(${target} ${scope} cxx_std_20)
        target_include_directories(${target} SYSTEM ${scope} "${imgui_SOURCE_DIR}" "${imgui_SOURCE_DIR}/backends")
        target_link_libraries(${target} ${scope} glfw OpenGL::GL)
        add_library(elf3d::third_party_imgui ALIAS ${target})
    elseif(target STREQUAL "elf3d")
        target_compile_features(${target} ${scope} cxx_std_20)
        target_include_directories(${target} ${scope} "${ELF3D_SOURCE_ROOT}/include")
        add_library(elf3d::elf3d ALIAS ${target})
    elseif(target STREQUAL "elf3d_model")
        target_compile_features(${target} ${scope} cxx_std_20)
        target_compile_definitions(${target} ${scope} ELF3D_STATIC)
        target_include_directories(${target} ${scope} "${ELF3D_SOURCE_ROOT}/include")
        elf3d_private_libraries(${target} elf3d_third_party_png elf3d_third_party_jpeg
            elf3d_third_party_cgltf elf3d_third_party_mikktspace)
        add_library(elf3d::model ALIAS ${target})
    elseif(target STREQUAL "elf3d_imgui")
        target_compile_features(${target} ${scope} cxx_std_20)
        target_include_directories(${target} ${scope} "${ELF3D_SOURCE_ROOT}/integrations/imgui/include")
        target_link_libraries(${target} ${scope} elf3d::elf3d elf3d::third_party_imgui)
        add_library(elf3d::imgui ALIAS ${target})
    endif()
endfunction()
